trigger: none

resources:
  pipelines:
    - pipeline: CI_Pipeline
      source: azure-pipeline-CI
      trigger:
        branches:
          include:
            - main

pool:
  name: self-hosted-linux

variables:
  IMAGE_NAME: ibrahimhefny/voting-app
  K8S_MANIFESTS_PATH: k8s/voting

stages:
  - stage: UpdateManifest
    displayName: Update Image Tag for ArgoCD
    jobs:
      - job: UpdateImageTag
        displayName: Update Deployment YAML
        steps:

          - checkout: self
            persistCredentials: true

          - script: |
              git config user.name "Ibrahimhefny"
              git config user.email "ibrahim.mo.hefny@gmail.com"
            displayName: Configure Git

          - script: |
              NEW_TAG=$(resources.pipeline.CI_Pipeline.runID)
              echo "New image tag: ${NEW_TAG}"

              # دايمًا خليك متزامن مع آخر main
              git fetch origin main
              git reset --hard origin/main

              # عدل الصورة
              sed -i "s|image: $(IMAGE_NAME):.*|image: $(IMAGE_NAME):${NEW_TAG}|g" $(K8S_MANIFESTS_PATH)/deployment.yaml

              git add $(K8S_MANIFESTS_PATH)/deployment.yaml
              git commit -m "Update image to build ${NEW_TAG} [skip ci]" || echo "No changes"

              # Push آمن
              git push origin HEAD:main --force-with-lease
            displayName: Update, Commit & Safe Push
